# Generated by Django 5.0.1 on 2024-01-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('thumb', models.ImageField(upload_to='')),
                ('icon', models.CharField(blank=True, choices=[('C', 'car'), ('F', 'foot')], default='C', help_text='На чем добираться?', max_length=1)),
            ],
        ),
    ]
