# Generated by Django 5.0.1 on 2024-01-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_card_amount_alter_card_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='gastronomy',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], default='n', help_text='Отметка для гастрономических маршрутов', max_length=1),
        ),
    ]
