# Generated by Django 5.0.1 on 2024-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_card_gastronomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wine',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], default='n', help_text='Будет ли что выпить?', max_length=1),
        ),
    ]
