# Generated by Django 5.0.1 on 2024-01-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_tag_card_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
