# Generated by Django 5.0.1 on 2024-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='neuro_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
