# Generated by Django 5.0.1 on 2024-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_post_description_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
